apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket-from-crossplane
spec:
  forProvider:
    locationConstraint: us-east-1
    objectOwnership: BucketOwnerEnforced
  providerConfigRef:
    name: default
